import type { Property } from './types';

const properties: Property[] = [
  {
    id: 1,
    title: 'Modern Villa in the Hills',
    price: 1200000,
    address: '123 Hillside Dr',
    city: 'Beverly Hills',
    state: 'CA',
    zip: '90210',
    beds: 4,
    baths: 5,
    sqft: 4500,
    type: 'House',
    description: 'A stunning modern villa with panoramic views of the city. Features an infinity pool, home theater, and a spacious open-plan living area. Perfect for entertaining.',
    images: [
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
    ],
    amenities: ['Infinity Pool', 'Home Theater', 'City Views', '2-Car Garage', 'Gourmet Kitchen'],
    agent: {
      name: 'John Realtor',
      email: 'john.realtor@terraabode.com',
      phone: '555-123-4567',
      avatar: 'https://placehold.co/100x100',
    },
  },
  {
    id: 2,
    title: 'Cozy Downtown Apartment',
    price: 750000,
    address: '456 Market St, Apt 12',
    city: 'San Francisco',
    state: 'CA',
    zip: '94105',
    beds: 2,
    baths: 2,
    sqft: 1200,
    type: 'Apartment',
    description: 'Chic and stylish apartment in the heart of the city. Walking distance to shops, restaurants, and public transport. Features updated appliances and hardwood floors.',
    images: [
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
    ],
    amenities: ['Hardwood Floors', 'Updated Appliances', 'Walk-in Closet', 'City Views'],
    agent: {
      name: 'Jane Agent',
      email: 'jane.agent@terraabode.com',
      phone: '555-987-6543',
      avatar: 'https://placehold.co/100x100',
    },
  },
  {
    id: 3,
    title: 'Suburban Family Home',
    price: 850000,
    address: '789 Oak Ave',
    city: 'Palo Alto',
    state: 'CA',
    zip: '94301',
    beds: 5,
    baths: 3,
    sqft: 3000,
    type: 'House',
    description: 'Spacious family home in a quiet, friendly neighborhood. Large backyard with a deck, perfect for summer barbecues. Close to top-rated schools and parks.',
    images: [
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
    ],
    amenities: ['Large Backyard', 'Deck', 'Fireplace', '3-Car Garage', 'Good Schools'],
    agent: {
      name: 'John Realtor',
      email: 'john.realtor@terraabode.com',
      phone: '555-123-4567',
      avatar: 'https://placehold.co/100x100',
    },
  },
  {
    id: 4,
    title: 'Luxury Waterfront Condo',
    price: 2500000,
    address: '101 Bay Shore Blvd, Unit 801',
    city: 'Miami',
    state: 'FL',
    zip: '33131',
    beds: 3,
    baths: 4,
    sqft: 3500,
    type: 'Condo',
    description: 'Breathtaking ocean views from every room. This luxury condo offers premium amenities including a private beach, fitness center, and 24-hour concierge service.',
    images: [
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
    ],
    amenities: ['Ocean Views', 'Private Beach Access', 'Fitness Center', '24h Concierge'],
    agent: {
      name: 'Angela Estates',
      email: 'angela.estates@terraabode.com',
      phone: '555-321-7654',
      avatar: 'https://placehold.co/100x100',
    },
  },
  {
    id: 5,
    title: 'Rustic Mountain Cabin',
    price: 600000,
    address: '234 Pinecone Ln',
    city: 'Aspen',
    state: 'CO',
    zip: '81611',
    beds: 3,
    baths: 2,
    sqft: 1800,
    type: 'House',
    description: 'A charming and rustic cabin retreat. Nestled in the mountains, this home offers peace and tranquility, with easy access to ski slopes and hiking trails.',
    images: [
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
    ],
    amenities: ['Mountain Views', 'Ski-in/Ski-out Access', 'Stone Fireplace', 'Hot Tub'],
    agent: {
      name: 'Jane Agent',
      email: 'jane.agent@terraabode.com',
      phone: '555-987-6543',
      avatar: 'https://placehold.co/100x100',
    },
  },
  {
    id: 6,
    title: 'Modern Townhouse with Rooftop Deck',
    price: 950000,
    address: '567 Urban Way',
    city: 'Austin',
    state: 'TX',
    zip: '78704',
    beds: 3,
    baths: 3,
    sqft: 2200,
    type: 'Townhouse',
    description: 'Sleek, modern townhouse in a vibrant neighborhood. The highlight is a private rooftop deck with stunning city skyline views, perfect for entertaining.',
    images: [
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
    ],
    amenities: ['Rooftop Deck', 'City Views', 'Smart Home System', 'Attached Garage'],
    agent: {
      name: 'John Realtor',
      email: 'john.realtor@terraabode.com',
      phone: '555-123-4567',
      avatar: 'https://placehold.co/100x100',
    },
  },
  {
    id: 7,
    title: 'Historic Brownstone',
    price: 1800000,
    address: '321 Cobblestone Rd',
    city: 'Boston',
    state: 'MA',
    zip: '02116',
    beds: 4,
    baths: 3,
    sqft: 2800,
    type: 'Townhouse',
    description: 'Live in a piece of history. This beautifully preserved brownstone combines historic charm with modern updates. Features original moldings and a gourmet kitchen.',
    images: [
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
    ],
    amenities: ['Historic Details', 'Gourmet Kitchen', 'Private Garden', '2 Fireplaces'],
    agent: {
      name: 'Angela Estates',
      email: 'angela.estates@terraabode.com',
      phone: '555-321-7654',
      avatar: 'https://placehold.co/100x100',
    },
  },
  {
    id: 8,
    title: 'Eco-Friendly Smart Home',
    price: 1100000,
    address: '789 Greenleaf Ct',
    city: 'Portland',
    state: 'OR',
    zip: '97201',
    beds: 4,
    baths: 3,
    sqft: 3100,
    type: 'House',
    description: 'A sustainable and energy-efficient home for the modern family. Equipped with solar panels, rainwater harvesting system, and full smart home automation.',
    images: [
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
      'https://placehold.co/800x600',
    ],
    amenities: ['Solar Panels', 'Rainwater Harvesting', 'Smart Home System', 'EV Charger'],
    agent: {
      name: 'Jane Agent',
      email: 'jane.agent@terraabode.com',
      phone: '555-987-6543',
      avatar: 'https://placehold.co/100x100',
    },
  },
];

export function getProperties(): Property[] {
  return properties;
}

export function getPropertyById(id: number): Property | undefined {
  return properties.find((p) => p.id === id);
}
